change make to build
tue-robotics/emc-env pull request #27
Opened 2023-02-09 16:03 UTC by PetervDooren

2023-02-09 16:14 UTC, MatthijsBurgh commented on install.bash
> +if ! dpkg -s python3-catkin-tools &> /dev/null
You need ROS apt sources for this. Or install via pip.

2023-02-09 16:29 UTC, MatthijsBurgh requested changes
This will produce too much log lines in CI, need to use `--no-status` in CI.

2023-02-10 09:31 UTC, MatthijsBurgh commented on setup/emc-update-impl.bash
> +catkin build --workspace "$EMC_SYSTEM_DIR" --no-status
I do think you want the status outside CI. So this should be conditional based on CI env variabele.

2023-02-10 09:54 UTC, MatthijsBurgh commented
CI doesn't fail on the build failing.

2023-02-10 10:06 UTC, MatthijsBurgh commented
Sadly `tf` is still needed because of `tf` conversions in geolib. Getting rid of this requires migrating the users of these to migrate to `tf2` conversions.

2023-02-10 10:15 UTC, PetervDooren commented
Mad issue https://github.com/tue-robotics/emc-env/issues/28 for CI not failing on a failed build

2023-02-10 10:44 UTC, MatthijsBurgh approved these changes
CI bugs will be fixed in another branch

2023-02-10 12:28 UTC, merged